### ISSUE TITLE
Respuesta de Cotización duplicada

### ISSUE THREAD

**Issue by vicentveg** [ivansabik/estafeta-api#13]
Hola, otra vez aquí pero esta vez ya no es por un error de ejecución si no por lo siguiente: cuando ejecuto la cotización de la siguiente forma el arreglo de la respuesta me trae la información duplicada en sus elementos y por lo tanto es inútil.
`$result		= $paq->cotizacion( '01210','86035','paquete','1','1','1','1' );
			echo "result = "; var_dump($result); echo "<br><br>";`

Aquello imprime:
```php
result = array(1) { ["costos"]=> array(4) { [0]=> array(8) { ["producto"]=> string(5) "11:30" ["peso_kg"]=> string(5) "11:30" ["tarifa_guia"]=> string(5) "11:30" ["tarifa_combustible"]=> string(5) "11:30" ["cargos_extra"]=> string(5) "11:30" ["sobrepeso_costo"]=> string(5) "11:30" ["sobrepeso_combustible"]=> string(5) "11:30" ["costo_total"]=> string(5) "11:30" } [1]=> array(8) { ["producto"]=> string(8) "Dia Sig." ["peso_kg"]=> string(8) "Dia Sig." ["tarifa_guia"]=> string(8) "Dia Sig." ["tarifa_combustible"]=> string(8) "Dia Sig." ["cargos_extra"]=> string(8) "Dia Sig." ["sobrepeso_costo"]=> string(8) "Dia Sig." ["sobrepeso_combustible"]=> string(8) "Dia Sig." ["costo_total"]=> string(8) "Dia Sig." } [2]=> array(8) { ["producto"]=> string(6) "2 Dias" ["peso_kg"]=> string(6) "2 Dias" ["tarifa_guia"]=> string(6) "2 Dias" ["tarifa_combustible"]=> string(6) "2 Dias" ["cargos_extra"]=> string(6) "2 Dias" ["sobrepeso_costo"]=> string(6) "2 Dias" ["sobrepeso_combustible"]=> string(6) "2 Dias" ["costo_total"]=> string(6) "2 Dias" } [3]=> array(8) { ["producto"]=> string(9) "Terrestre" ["peso_kg"]=> string(9) "Terrestre" ["tarifa_guia"]=> string(9) "Terrestre" ["tarifa_combustible"]=> string(9) "Terrestre" ["cargos_extra"]=> string(9) "Terrestre" ["sobrepeso_costo"]=> string(9) "Terrestre" ["sobrepeso_combustible"]=> string(9) "Terrestre" ["costo_total"]=> string(9) "Terrestre" } } } 
```

Saludos.

**Comment by ivansabik** [comment]
tambien tiene que ver con validacion de parametros, en vez de 1,1,1,1 intenta con el ejemplo del README

`http://localhost:8000/index.php/estafeta/cotizacion?cp_origen=01210&cp_destino=86035&tipo=paquete&peso=1&alto=10&ancho=20&largo=20`

**Comment by vicentveg** [comment]
Nope, acabo de hacer una prueba con los datos del Readme:
peso=1, alto=10, largo=20 y ancho=20 
Y sale el vardump del resultado final::
`" result = array(1) { ["costos"]=> array(4) { [0]=> array(8) { ["producto"]=> string(5) "11:30" ["peso_kg"]=> string(5) "11:30" ["tarifa_guia"]=> string(5) "11:30" ["tarifa_combustible"]=> string(5) "11:30" ["cargos_extra"]=> string(5) "11:30" ["sobrepeso_costo"]=> string(5) "11:30" ["sobrepeso_combustible"]=> string(5) "11:30" ["costo_total"]=> string(5) "11:30" } [1]=> array(8) { ["producto"]=> string(8) "Dia Sig." ["peso_kg"]=> string(8) "Dia Sig." ["tarifa_guia"]=> string(8) "Dia Sig." ["tarifa_combustible"]=> string(8) "Dia Sig." ["cargos_extra"]=> string(8) "Dia Sig." ["sobrepeso_costo"]=> string(8) "Dia Sig." ["sobrepeso_combustible"]=> string(8) "Dia Sig." ["costo_total"]=> string(8) "Dia Sig." } [2]=> array(8) { ["producto"]=> string(6) "2 Dias" ["peso_kg"]=> string(6) "2 Dias" ["tarifa_guia"]=> string(6) "2 Dias" ["tarifa_combustible"]=> string(6) "2 Dias" ["cargos_extra"]=> string(6) "2 Dias" ["sobrepeso_costo"]=> string(6) "2 Dias" ["sobrepeso_combustible"]=> string(6) "2 Dias" ["costo_total"]=> string(6) "2 Dias" } [3]=> array(8) { ["producto"]=> string(9) "Terrestre" ["peso_kg"]=> string(9) "Terrestre" ["tarifa_guia"]=> string(9) "Terrestre" ["tarifa_combustible"]=> string(9) "Terrestre" ["cargos_extra"]=> string(9) "Terrestre" ["sobrepeso_costo"]=> string(9) "Terrestre" ["sobrepeso_combustible"]=> string(9) "Terrestre" ["costo_total"]=> string(9) "Terrestre" } } } `

Sin embargo si hago un vardump directo a lo que trae la petición curl me da como resultado los datos correctos de estafeta en la siguiente tabla:

http://www.subirimagenes.com/imagedata.php?url=http://s2.subirimagenes.com/imagen/9568323untitled.png

Creo que hay algo mal cuando intentas quitar la tabla y demás basura en las variables strHeadersRespuesta y strHtmlObjetivo, voy a hacerle cambios a ver si lo arreglo por mi cuenta pero te lo menciono para que lo tengas en cuenta.

**Comment by ivansabik** [comment]
Perfecto, para cuando quieras ver qué está haciendo el código o debería hacer te recomiendo veas los tests:

https://github.com/ivansabik/estafeta-api/blob/master/Tests/CotizacionTest.php

**Comment by Ganacontrol** [comment]
Perdón por irrumpir por aquí, podrían decirme si es posible conectar Estafeta con Woocommerce en Wordpress para calculo de envios / rastreo etc?

**Comment by ivansabik** [comment]
No es algo que sepa quién lo ha hecho pero puede tendrías que hacer un plugin o algo similar, te recomiendo mejor ésto es más sencillo para ese caso pero no está tan desarrollado como este proyecto:

https://github.com/ivansabik/estafeta-php
